name: request pr review

on:
  schedule:
    - cron: '0 10 * * *' # 매일 오전 10시마다 수행

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Request PR Review
        uses: naver/request-pr-review@v1.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          slackBotToken: ${{ secrets.SLACK_BOT_TOKEN }}
          repoUrl: 'https://github.com/cocoon-hub/timinggame-api'